In [ ]:
5+8

13

In [ ]:
###########  Mean,median,mode
                -numpy
                -Pandas
                -statistics
                -scipy

In [ ]:
#Using Numpy
#import the necssary libraries:
import numpy as np


In [ ]:
#insert  the data

In [ ]:
import numpy as np
data=[32,30,24,20,5,30,60,10,75]
mean=np.mean(data)
print(mean)

31.77777777777778


In [ ]:
import numpy as np
data=[32,30,24,20,5,30,60,10,75]
median=np.median(data)
print(median)

30.0


In [ ]:
import numpy as np
data=[32,30,24,20,5,30,60,10,75]
mode=np.bincount(data).argmax()
print(mode)

30


In [ ]:
#create  a csv dataset
#import pandas as pd

In [ ]:
import pandas as pd
data={
    'name':['rasi','susi','ajay','harasha','chinu'],
    'Height':[175,289,445,23,544],
    'age':[22,33,44,55,66]
}
df=pd.DataFrame(data)
df.to_csv('data.csv')

In [ ]:
df

name  Height  age
0     rasi     175   22
1     susi     289   33
2     ajay     445   44
3  harasha      23   55
4    chinu     544   66

In [ ]:
print("rasi")

rasi


In [ ]:
#Data pre-processes
import pandas as pd
df=pd.read_csv('/content/HumanBodyPerformance.csv')
print(df)

        age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0      27.0      M      172.3      75.24        21.3       80.0     130.0   
1      25.0      M      165.0      55.80        15.7       77.0     126.0   
2      31.0      M      179.6      78.00        20.1       92.0     152.0   
3      32.0      M      174.5      71.10        18.4       76.0     147.0   
4      28.0      M      173.8      67.70        17.1       70.0     127.0   
...     ...    ...        ...        ...         ...        ...       ...   
13388  25.0      M      172.1      71.80        16.2       74.0     141.0   
13389  21.0      M      179.7      63.90        12.1       74.0     128.0   
13390  39.0      M      177.2      80.50        20.1       78.0     132.0   
13391  64.0      F      146.1      57.70        40.4       68.0     121.0   
13392  34.0      M      164.0      66.10        19.5       82.0     150.0   

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm cl

In [ ]:
df.shape

(13393, 12)

In [ ]:
df.head()

age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0  27.0      M      172.3      75.24        21.3       80.0     130.0   
1  25.0      M      165.0      55.80        15.7       77.0     126.0   
2  31.0      M      179.6      78.00        20.1       92.0     152.0   
3  32.0      M      174.5      71.10        18.4       76.0     147.0   
4  28.0      M      173.8      67.70        17.1       70.0     127.0   

   gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm class  
0       54.9                     18.4            60.0          217.0     C  
1       36.4                     16.3            53.0          229.0     A  
2       44.8                     12.0            49.0          181.0     C  
3       41.4                     15.2            53.0          219.0     B  
4       43.5                     27.1            45.0          217.0     B

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13393 entries, 0 to 13392
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      13393 non-null  float64
 1   gender                   13393 non-null  object 
 2   height_cm                13393 non-null  float64
 3   weight_kg                13393 non-null  float64
 4   body fat_%               13393 non-null  float64
 5   diastolic                13393 non-null  float64
 6   systolic                 13393 non-null  float64
 7   gripForce                13393 non-null  float64
 8   sit and bend forward_cm  13393 non-null  float64
 9   sit-ups counts           13393 non-null  float64
 10  broad jump_cm            13393 non-null  float64
 11  class                    13393 non-null  object 
dtypes: float64(10), object(2)
memory usage: 1.2+ MB


In [ ]:
df.describe()

age     height_cm     weight_kg    body fat_%     diastolic  \
count  13393.000000  13393.000000  13393.000000  13393.000000  13393.000000   
mean      36.775106    168.559807     67.447316     23.240165     78.796842   
std       13.625639      8.426583     11.949666      7.256844     10.742033   
min       21.000000    125.000000     26.300000      3.000000      0.000000   
25%       25.000000    162.400000     58.200000     18.000000     71.000000   
50%       32.000000    169.200000     67.400000     22.800000     79.000000   
75%       48.000000    174.800000     75.300000     28.000000     86.000000   
max       64.000000    193.800000    138.100000     78.400000    156.200000   

           systolic     gripForce  sit and bend forward_cm  sit-ups counts  \
count  13393.000000  13393.000000             13393.000000    13393.000000   
mean     130.234817     36.963877                15.209268       39.771224   
std       14.713954     10.624864                 8.456677       14.276698   
min        0.000000      0.000000               -25.000000        0.000000   
25%      120.000000     27.500000                10.900000       30.000000   
50%      130.000000     37.900000                16.200000       41.000000   
75%      141.000000     45.200000                20.700000       50.000000   
max      201.000000     70.500000               213.000000       80.000000   

       broad jump_cm  
count   13393.000000  
mean      190.129627  
std        39.868000  
min         0.000000  
25%       162.000000  
50%       193.000000  
75%       221.000000  
max       303.000000

In [ ]:
#count missing:
df.isnull()

age  gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0      False   False      False      False       False      False     False   
1      False   False      False      False       False      False     False   
2      False   False      False      False       False      False     False   
3      False   False      False      False       False      False     False   
4      False   False      False      False       False      False     False   
...      ...     ...        ...        ...         ...        ...       ...   
13388  False   False      False      False       False      False     False   
13389  False   False      False      False       False      False     False   
13390  False   False      False      False       False      False     False   
13391  False   False      False      False       False      False     False   
13392  False   False      False      False       False      False     False   

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm  \
0          False                    False           False          False   
1          False                    False           False          False   
2          False                    False           False          False   
3          False                    False           False          False   
4          False                    False           False          False   
...          ...                      ...             ...            ...   
13388      False                    False           False          False   
13389      False                    False           False          False   
13390      False                    False           False          False   
13391      False                    False           False          False   
13392      False                    False           False          False   

       class  
0      False  
1      False  
2      False  
3      False  
4      False  
...      ...  
13388  False  
13389  False  
13390  False  
13391  False  
13392  False  

[13393 rows x 12 columns]

In [ ]:
df.isnull().sum()

age                        0
gender                     0
height_cm                  0
weight_kg                  0
body fat_%                 0
diastolic                  0
systolic                   0
gripForce                  0
sit and bend forward_cm    0
sit-ups counts             0
broad jump_cm              0
class                      0
dtype: int64

In [ ]:
df.isnull().sum().sum()

0

In [ ]:
df['age'].mean()

36.77510639886508

In [ ]:
#question:write the code to read the middle data set

In [ ]:
df.age

0        27.0
1        25.0
2        31.0
3        32.0
4        28.0
         ... 
13388    25.0
13389    21.0
13390    39.0
13391    64.0
13392    34.0
Name: age, Length: 13393, dtype: float64

In [ ]:
df.columns

Index(['age', 'gender', 'height_cm', 'weight_kg', 'body fat_%', 'diastolic',
       'systolic', 'gripForce', 'sit and bend forward_cm', 'sit-ups counts',
       'broad jump_cm', 'class'],
      dtype='object')

In [ ]:
df['sit-ups counts'].mean()

39.77122377361308

In [ ]:
df['sit-ups counts'].mode()

0    45.0
Name: sit-ups counts, dtype: float64

In [ ]:
df.dtypes

age                        float64
gender                      object
height_cm                  float64
weight_kg                  float64
body fat_%                 float64
diastolic                  float64
systolic                   float64
gripForce                  float64
sit and bend forward_cm    float64
sit-ups counts             float64
broad jump_cm              float64
class                       object
dtype: object

In [ ]:
#Gert the count of unique in a specific  columns:

In [ ]:
df['age'].value_counts()

age
21.0    964
22.0    789
23.0    668
25.0    644
26.0    629
24.0    617
27.0    546
28.0    527
29.0    407
30.0    374
60.0    368
31.0    338
37.0    282
32.0    275
62.0    265
61.0    254
39.0    243
36.0    239
38.0    230
63.0    230
34.0    229
33.0    229
35.0    223
41.0    217
64.0    215
40.0    211
56.0    197
48.0    196
59.0    192
43.0    192
51.0    191
50.0    189
55.0    185
45.0    183
46.0    181
57.0    181
58.0    180
42.0    179
47.0    172
44.0    172
49.0    163
54.0    152
52.0    140
53.0    135
Name: count, dtype: int64

In [ ]:
df['age'].count()

13393

In [ ]:
df["gender"].value_counts()

gender
M    8467
F    4926
Name: count, dtype: int64

In [ ]:
df.shape

(13393, 12)

In [ ]:
df.nunique()

age                          44
gender                        2
height_cm                   467
weight_kg                  1398
body fat_%                  527
diastolic                    89
systolic                    102
gripForce                   550
sit and bend forward_cm     528
sit-ups counts               81
broad jump_cm               245
class                         4
dtype: int64

In [ ]:
df['age'].unique()

array([27., 25., 31., 32., 28., 36., 42., 33., 54., 57., 22., 24., 45.,
       26., 21., 59., 38., 44., 23., 62., 47., 48., 50., 30., 49., 40.,
       52., 39., 34., 58., 43., 56., 37., 63., 35., 60., 51., 41., 46.,
       29., 61., 55., 64., 53.])

In [ ]:
df['age'].nunique()

44

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
13388    False
13389    False
13390    False
13391    False
13392    False
Length: 13393, dtype: bool

In [ ]:
df.duplicated().sum()

1

In [ ]:
df.drop_duplicates()

age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0      27.0      M      172.3      75.24        21.3       80.0     130.0   
1      25.0      M      165.0      55.80        15.7       77.0     126.0   
2      31.0      M      179.6      78.00        20.1       92.0     152.0   
3      32.0      M      174.5      71.10        18.4       76.0     147.0   
4      28.0      M      173.8      67.70        17.1       70.0     127.0   
...     ...    ...        ...        ...         ...        ...       ...   
13388  25.0      M      172.1      71.80        16.2       74.0     141.0   
13389  21.0      M      179.7      63.90        12.1       74.0     128.0   
13390  39.0      M      177.2      80.50        20.1       78.0     132.0   
13391  64.0      F      146.1      57.70        40.4       68.0     121.0   
13392  34.0      M      164.0      66.10        19.5       82.0     150.0   

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm class  
0           54.9                     18.4            60.0          217.0     C  
1           36.4                     16.3            53.0          229.0     A  
2           44.8                     12.0            49.0          181.0     C  
3           41.4                     15.2            53.0          219.0     B  
4           43.5                     27.1            45.0          217.0     B  
...          ...                      ...             ...            ...   ...  
13388       35.8                     17.4            47.0          198.0     C  
13389       33.0                      1.1            48.0          167.0     D  
13390       63.5                     16.4            45.0          229.0     A  
13391       19.3                      9.2             0.0           75.0     D  
13392       35.9                      7.1            51.0          180.0     C  

[13392 rows x 12 columns]

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.shape

(13392, 12)

In [ ]:
#How manynumerical and categorical data are there:

In [ ]:
categotical=df.select_dtypes(include='object')

In [ ]:
categotical

gender class
0          M     C
1          M     A
2          M     C
3          M     B
4          M     B
...      ...   ...
13388      M     C
13389      M     D
13390      M     A
13391      F     D
13392      M     C

[13392 rows x 2 columns]

In [ ]:
#1.min_MaxNormaliztion
#1.1 import the necessarrey:

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [ ]:
#1.2 creat the dataset:

In [ ]:
import pandas as pd
data={'bedroom':[1,2,3,4,5],
      'bathroom':[21,2,2,3,2],
      'sqrt_living':[500,1000,1500,2000,2500],
      'agr_of_the_housh':[5,10,15,20,25],
      'price':[10000,20000,30000,40000,50000]}
data

{'bedroom': [1, 2, 3, 4, 5],
 'bathroom': [21, 2, 2, 3, 2],
 'sqrt_living': [500, 1000, 1500, 2000, 2500],
 'agr_of_the_housh': [5, 10, 15, 20, 25],
 'price': [10000, 20000, 30000, 40000, 50000]}

In [ ]:
df=pd.DataFrame(data)
print(df)

   bedroom  bathroom  sqrt_living  agr_of_the_housh  price
0        1        21          500                 5  10000
1        2         2         1000                10  20000
2        3         2         1500                15  30000
3        4         3         2000                20  40000
4        5         2         2500                25  50000


In [ ]:
#1.3 Apply the Min_Max normalization

In [ ]:
scaler=MinMaxScaler()

In [ ]:
scaler=MinMaxScaler()
df_scaled=scaler.fit_transform(df)
df_scaled

array([[0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.25      , 0.        , 0.25      , 0.25      , 0.25      ],
       [0.5       , 0.        , 0.5       , 0.5       , 0.5       ],
       [0.75      , 0.05263158, 0.75      , 0.75      , 0.75      ],
       [1.        , 0.        , 1.        , 1.        , 1.        ]])

In [ ]:
min=np.min(data)

In [ ]:
max=np.max(data)

In [ ]:
import numpy as np
data=[200,300,400,500,600]
standard=np.std(data)
print(standard)

141.4213562373095


In [ ]:
means=np.mean(data)
means=(data-means)/standard
means

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [ ]:
#1.4:fit

In [ ]:
normalized_data=scaler.fit_transform(df)
normalized_data

array([[0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.25      , 0.        , 0.25      , 0.25      , 0.25      ],
       [0.5       , 0.        , 0.5       , 0.5       , 0.5       ],
       [0.75      , 0.05263158, 0.75      , 0.75      , 0.75      ],
       [1.        , 0.        , 1.        , 1.        , 1.        ]])

In [ ]:
#1.5 :convert the array pd.DataFrame

In [ ]:
normalized_convert=pd.DataFrame(normalized_data,columns=df.columns)
normalized_convert


bedroom  bathroom  sqrt_living  agr_of_the_housh  price
0     0.00  1.000000         0.00              0.00   0.00
1     0.25  0.000000         0.25              0.25   0.25
2     0.50  0.000000         0.50              0.50   0.50
3     0.75  0.052632         0.75              0.75   0.75
4     1.00  0.000000         1.00              1.00   1.00

# 2.Score *Normalizatioon*

1.1import the Necessary Library:

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import FunctionTransformer

## ***1.2***creat the dataset:

In [ ]:
data={'bedroom':[1,2,3,4,5],
      'bathroom':[21,2,2,3,2],
      'sqrt_living':[500,1000,1500,2000,2500],
      'agr_of_the_housh':[5,10,15,20,25],
      'price':[10000,20000,30000,40000,50000]}
data

{'bedroom': [1, 2, 3, 4, 5],
 'bathroom': [21, 2, 2, 3, 2],
 'sqrt_living': [500, 1000, 1500, 2000, 2500],
 'agr_of_the_housh': [5, 10, 15, 20, 25],
 'price': [10000, 20000, 30000, 40000, 50000]}

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler

StandardScaler()

In [ ]:
normalized_data=scaler.fit_transform(df)
normalized_data

array([[-1.41421356,  1.99733865, -1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.53262364, -0.70710678, -0.70710678, -0.70710678],
       [ 0.        , -0.53262364,  0.        ,  0.        ,  0.        ],
       [ 0.70710678, -0.39946773,  0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356, -0.53262364,  1.41421356,  1.41421356,  1.41421356]])

In [ ]:
data=

#convert it in to array to DataFrame:

In [ ]:
Noramlized=pd.DataFrame(normalized_data,columns=df.columns)
Noramlized

bedroom  bathroom  sqrt_living  agr_of_the_housh     price
0 -1.414214  1.997339    -1.414214         -1.414214 -1.414214
1 -0.707107 -0.532624    -0.707107         -0.707107 -0.707107
2  0.000000 -0.532624     0.000000          0.000000  0.000000
3  0.707107 -0.399468     0.707107          0.707107  0.707107
4  1.414214 -0.532624     1.414214          1.414214  1.414214

In [ ]:
import numpy as np
def decimal_scaling(data):
  max_value=np.max(np.abs(data))
  num_digits=len(str(int(max_value)))
  scaling_factor=10*num_digits
  scaled_data=data/scaling_factor
  return scaled_data
data=np.array([200,300,400,600,1000])
scaled_data=decimal_scaling(data)
print("OrigiNAL DATA:",data)
print("scaled data:",scaled_data)

OrigiNAL DATA: [ 200  300  400  600 1000]
scaled data: [ 5.   7.5 10.  15.  25. ]


#create the DEcimal_scaler Library by our ownsel.

In [ ]:
def decimal_scaling(X):
  Max_abv=np.max(np.abs(X))
  scale=10**np.ceil(np.log10(max_abv))
  return X/scale

In [ ]:
transformer=FunctionTransformer(decimal_scaling)

In [ ]:
decimal_scaling=transformer.fit_transform(df)
decimal_scaling

NameError: name 'max_abv' is not defined